#!/usr/bin/env python3
"""Extract docs/VoiceLive 2 Manual v1-5.pdf to markdown."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PDF = ROOT / "docs" / "VoiceLive 2 Manual v1-5.pdf"
OUT = ROOT / "docs" / "VoiceLive-2-Manual-v1-5.md"


def main() -> int:
    try:
        from pypdf import PdfReader
    except ImportError:
        print("Install pypdf: python3 -m venv .venv-pdf && .venv-pdf/bin/pip install pypdf", file=sys.stderr)
        return 1

    if not PDF.is_file():
        print(f"Missing PDF: {PDF}", file=sys.stderr)
        return 1

    reader = PdfReader(str(PDF))
    pages: list[str] = []
    for page in reader.pages:
        text = page.extract_text() or ""
        text = re.sub(r"\r\n?", "\n", text)
        text = re.sub(r"[ \t]+\n", "\n", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        pages.append(text.strip())

    toc_lines: list[str] = []
    body: list[str] = []
    for i, text in enumerate(pages, start=1):
        anchor = f"page-{i}"
        toc_lines.append(f"- [Page {i}](#{anchor})")
        body.append(f"## Page {i} {{#{anchor}}}\n\n{text}\n")

    md = f"""# TC-Helicon VoiceLive 2 — User Manual (v1.5)

| | |
|---|---|
| **Source PDF** | [VoiceLive 2 Manual v1-5.pdf](./VoiceLive%202%20Manual%20v1-5.pdf) |
| **Pages** | {len(pages)} |
| **Extracted** | Auto-generated by `scripts/extract-voicelive2-manual.py` |

> **Editor note:** VoiceLive Touch v1 shares the same SysEx parameter model. Use this manual for **UI grouping**, **MIDI CC labels** (pp. 98–100), and **Harmony / NaturalPlay** concepts. SysEx IDs: [VoiceLive-Touch-Sysex-Manual.md](./VoiceLive-Touch-Sysex-Manual.md).

---

## Table of contents

{chr(10).join(toc_lines)}

---

{chr(10).join(body)}
"""

    OUT.write_text(md, encoding="utf-8")
    print(f"Wrote {OUT} ({len(pages)} pages, {len(md):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
